services:
    poker.front:
        container_name: poker-front
        image: 'node:24.0.1-alpine3.20'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        networks:
            - poker_app
        volumes:
            - './poker-front:/var/www/html'
        working_dir: '/var/www/html'
        command: sh -c "npm install && npm run dev"
        environment:
            - VITE_ORIGIN=http://localhost:5173
            - VITE_PORT=5173

    poker.back:
        container_name: poker-api
        image: 'node:24.0.1-alpine3.20'
        networks:
            - poker_app
        volumes:
            - './Poker-API:/var/www/html'
        ports:
            - '8080:3000'
        working_dir: '/var/www/html'
        command: sh -c "npm install && npm run start:dev"
        healthcheck:
            test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3000/api" ]
            interval: 10s
            timeout: 5s
            retries: 50
            start_period: 10s
networks:
    poker_app:
        external: false
volumes:
    poker_data:
        driver: local
